project:
  type: website
  output-dir: docs

website:
  title: "Kathryn Kolb"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about_me.qmd
        text: About Me
      - href: posts.qmd
        text: Projects
      - href: summer_plans.qmd
        text: Summer Plans
      - href: CV.qmd
        text: CV

format:
  html:
    theme: 
    - cosmo
    - styles.scss
    mainfont: Outfit
    toc: true
    page-layout: full

editor: visual

