project:
  type: website
  output-dir: docs

website:
  title: "Kathryn Kolb"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - about_me.qmd

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true
    page-layout: full

editor: visual

